* Domovik
This is the companion extension to the [[https://domovik.app][Domovik]] cross-browser synchronisation service.

It comes in two flavors: /Domovik/ provides a New Tab Page featuring your synchronized data, and /Domovik Lite/, which does not change your New Tab Page.

* Download the extension
- [[https://addons.mozilla.org/en-US/firefox/user/16143812/][For Firefox]]
- [[https://chrome.google.com/webstore/search/domovik][For Chrome-based browsers]]
- [[https://microsoftedge.microsoft.com/addons/search/domovik][For Edge]]

* Build the extension
** Requirements
A local installation of [[https://nodejs.org/en/][Node.js]] is required to build the extension, which is needed to compile the [[https://www.typescriptlang.org/][TypeScript]] source files and run the [[https://webpack.js.org/][webpack]] build system. Once it is available, you can clone the repository:

#+begin_src
git clone https://github.com/domovikapp/domovik-webext.git
#+end_src

then install the required JS modules:

#+begin_src
npm install
#+end_src

** Domovik Full and Lite
The Domovik extensions supports two build profiles: /full/ and /lite/. The only difference between them is that /full/ add a custom New Tab page, whereas the /lite/ version does not make any change to it.

** Release
The release version of the web extension is built with =make full= (or =make lite=). The release files will then be available in the =dist/= folder, from where they can be packaged for distribution.

** Development
I you wish to hack on the Domovik web extension, you can run it in development mode with =make dev_full= (or =make dev_lite=). The built extension will then be available in the =dist_dev/= folder, from which it can be side-loaded in your browser.

** License
The Domovik web extension is released under the [[https://www.gnu.org/licenses/gpl-3.0.txt][GPLv3]] license.

** Changelog
** 1.5
- Follow the new additions to the API
- Add a toggle for custom server URL
** 1.4.7
- Add a debounce system to reduce bandwidth consumption
** 1.4.6
- Ensure that the trailing slash in server URL is there
- Add a better status indicator
- Fix redundant link sending
** 1.4.4
- Network bugfixes
** 1.4.3
- Add the version infos in the settings screen
- Add a link to the account settings in the settings screen
** 1.4.2
- Do not send overlapping token renewal requests
** 1.4.1
- Fix CSS for settings
- Don't erase existing configuration on update
** 1.4
- Widen the new tab page grid
- Add a lite version without the New Tab page
- Open Settings on install
- Add a Lite version which does not override the new tab page

* License
The Domovik web extensions are available under the [[http://www.gnu.org/licenses/agpl-3.0.html][GPLv3 license]], as found in the LICENSE text file.
